name: Update Main on Tag

on:
  push:
    tags:
      - '*' 

permissions:
  contents: write

jobs:
  update-main:
    runs-on: macos-latest

    steps:
      - name: Checkout package
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Switch to main
        run: git checkout main

      - name: Copy Sources from package
        run: git restore --source=package -- Sources

      - name: Commit changes
        run: |
          git add Sources
          git commit -m "Update Sources from package tag ${{ github.ref_name }}" || echo "No changes to commit"

      - name: Push to main
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Bearound/bearound-ios-sdk.git main
